import matplotlib.pyplot as plt
import numpy as np
import sbp_operators as ops
import scipy.sparse.linalg as spsplg
from scipy.sparse import block_diag, diags_array, hstack, identity, kron


def select_sbp_fun(order=5):
    """Pick the correct function from the sbp_operators module"""
    if order == 5:
        fun = ops.sbp_upwind_5th
    else:
        raise NotImplementedError(f"Order {order} not implemented.")
    return fun


def create_grid(mx, my, lim_x, lim_y):
    """
    Return a dict with grid-related matrices and vectors.
 
    #--- Example usage ---
    order = 5
    mx = 81
    my = 121
    lim_x = [-1, 1]
    lim_y = [0, 1]

    grid = create_grid(mx, my, lim_x, lim_y)

    grid['X'] # 2D array of x-coordinates
    grid['Y'] # 2D array of y-coordinates

    grid['Xv'] # Same values as grid['X'], but reshaped as a long 1D array
    grid['Yv'] # Same values as grid['Y'], but reshaped as a long 1D array

    grid['Xw'] # x-coordinates for points on the west boundary
    # Same for Y and s, e, n (south, east, north).
    #--------------------------------
    """
    mtot = mx * my
    xl, xr = lim_x
    yl, yr = lim_y
    hx = (xr - xl) / (mx - 1)
    hy = (yr - yl) / (my - 1)
    xvec = np.linspace(xl, xr, mx)
    yvec = np.linspace(yl, yr, my)

    # 2D arrays of gird-point coordinates
    X, Y = np.meshgrid(xvec, yvec)

    # Long 1D arrays
    Xv = X.reshape(mtot)
    Yv = Y.reshape(mtot)

    grid = {}
    grid["X"] = X
    grid["Y"] = Y
    grid["Xv"] = Xv
    grid["Yv"] = Yv
    grid["mx"] = mx
    grid["my"] = my
    grid["hx"] = hx
    grid["hy"] = hy

    # Boundary coordinates
    grid["Xw"] = X[:, 0]
    grid["Yw"] = Y[:, 0]

    grid["Xe"] = X[:, -1]
    grid["Ye"] = Y[:, -1]

    grid["Xs"] = X[0, :]
    grid["Ys"] = Y[0, :]

    grid["Xn"] = X[-1, :]
    grid["Yn"] = Y[-1, :]

    return grid


def assemble_matrices(grid, order, b=None, bc_opts=None):
    """
    Discretizes the Poisson equation using SBP-SAT.
    Returns a dict of SBP-related matrices.

    Parameters:
    grid    - generated by create_grid()
    order   - order of accuracy
    b       - variable coefficient in the Laplacian (omit for the regular Laplacian)
    bc_opts - dict specifying boundary condition 'type' ('dirichlet' or 'robin')

    Example usage:
    grid = generate_grid(...)
    order = 5

    sbp_discr = assemble_matrices(grid, order)

    sbp_discr['Laplace_with_BC'] # Full discretization matrix
    sbp_discr['H'] # SBP quadrature matrix
    sbp_discr['Dx_m'] # d/dx operator
    sbp_discr['Dy_m'] # d/dy operator
    ....
    # Many more operators available.
    """
    if bc_opts is None:
        bc_type = "dirichlet"
    else:
        bc_type = bc_opts["type"]

    my, mx = grid["X"].shape
    xl, xr = (min(grid["Xv"]), max(grid["Xv"]))
    yl, yr = (min(grid["Yv"]), max(grid["Yv"]))
    hx = (xr - xl) / (mx - 1)
    hy = (yr - yl) / (my - 1)

    # 1D SBP operators
    sbp_fun = select_sbp_fun(order)
    Hx, HIx, Dpx, Dmx, e_lx, e_rx, gamma_x = sbp_fun(mx, hx)
    Hy, HIy, Dpy, Dmy, e_ly, e_ry, gamma_y = sbp_fun(my, hy)

    # Build 1D boundary derivatives
    d1_lx = (e_lx.T @ Dmx).T
    d1_rx = (e_rx.T @ Dmx).T
    d1_ly = (e_ly.T @ Dmy).T
    d1_ry = (e_ry.T @ Dmy).T

    # Wrap kron function to set format
    my_kron = lambda A, B: kron(A, B, format="csc")

    # Extend 1D operators to 2D
    Ix = identity(mx, format="csc")
    Iy = identity(my, format="csc")
    Dx_p = my_kron(Iy, Dpx)
    Dx_m = my_kron(Iy, Dmx)
    Dy_p = my_kron(Dpy, Ix)
    Dy_m = my_kron(Dmy, Ix)
    H = my_kron(Hy, Hx)
    HI = my_kron(HIy, HIx)

    # Variable-coefficient Laplace operator, d_i b d_i
    if b is None:
        B = identity(mx * my, format="csc")
    else:
        B = diags_array(b)
    Laplace = Dx_p @ B @ Dx_m + Dy_p @ B @ Dy_m

    # Dictionary for useful operators/matrices
    ops = {}
    ops["order"] = order
    ops["H"] = H
    ops["HI"] = HI
    ops["B"] = B
    ops["Dx_m"] = Dx_m
    ops["Dy_m"] = Dy_m

    # Trace operators (transpose of)
    e_w = my_kron(Iy, e_lx)
    e_e = my_kron(Iy, e_rx)
    e_s = my_kron(e_ly, Ix)
    e_n = my_kron(e_ry, Ix)

    ops["e_w"] = e_w
    ops["e_e"] = e_e
    ops["e_s"] = e_s
    ops["e_n"] = e_n
    ops["e_bnd"] = hstack([e_w, e_s, e_e, e_n])

    # Normal trace operators (transpose of)
    dn_w = -my_kron(Iy, d1_lx)
    dn_e = my_kron(Iy, d1_rx)
    dn_s = -my_kron(d1_ly, Ix)
    dn_n = my_kron(d1_ry, Ix)

    ops["dn_w"] = dn_w
    ops["dn_e"] = dn_e
    ops["dn_s"] = dn_s
    ops["dn_n"] = dn_n
    ops["dn"] = hstack([dn_w, dn_s, dn_e, dn_n])

    # Tangential derivatives
    ops["dt_w"] = e_w.T @ Dy_m @ e_w
    ops["dt_e"] = e_e.T @ Dy_m @ e_e
    ops["dt_s"] = e_s.T @ Dx_m @ e_s
    ops["dt_n"] = e_n.T @ Dx_m @ e_n
    ops["Dt"] = block_diag([ops["dt_n"], ops["dt_s"], ops["dt_e"], ops["dt_n"]])

    # Face quadratures
    ops["H_s"] = Hx
    ops["H_n"] = Hx
    ops["H_w"] = Hy
    ops["H_e"] = Hy
    ops["H_bnd"] = block_diag([Hy, Hx, Hy, Hx])

    # Variable coefficient restricted to the boundary
    ops["B_bnd"] = block_diag(
        [e_w.T @ B @ e_w, e_s.T @ B @ e_s, e_e.T @ B @ e_e, e_n.T @ B @ e_n]
    )

    # Penalty strength required for Dirichlet BC
    gx = 1 / (gamma_x * hx)
    gy = 1 / (gamma_y * hy)
    ops["gamma"] = (
        gx * e_w @ e_w.T + gy * e_s @ e_s.T + gx * e_e @ e_e.T + gy * e_n @ e_n.T
    )

    # Get SATs for BC
    if bc_type == "dirichlet":
        total_closure, boundary_forcing = dirichlet_bc(ops)
    elif bc_type == "robin":
        total_closure, boundary_forcing = robin_bc(ops, bc_opts["a"])
    ops["Laplace_with_BC"] = Laplace + total_closure
    ops["boundary_forcing"] = boundary_forcing

    # Poisson solver
    ops["poisson_solver"] = lambda u: spsplg.spsolve(ops["Laplace_with_BC"], u)

    return ops


def dirichlet_bc(ops):
    """Used internally for the Dirichlet SAT"""
    tuning = 1.2  # tuning > 1 reguired for definiteness
    HI = ops["HI"]
    B = ops["B"]
    e = ops["e_bnd"]
    dn = ops["dn"]
    Bb = ops["B_bnd"]
    Hb = ops["H_bnd"]
    gamma = ops["gamma"]

    # Symmetric part
    closure = -tuning * gamma @ (HI @ (e @ Bb @ Hb @ e.T))
    penalty = -tuning * gamma @ (HI @ (e @ Bb @ Hb))

    # Symmetrizing part
    closure += HI @ (dn @ Bb @ Hb @ e.T)
    penalty += HI @ (dn @ Bb @ Hb)

    return closure, penalty


def robin_bc(ops, a=1):
    """Used internally for the Robin SAT"""
    HI = ops["HI"]
    e = ops["e_bnd"]
    dn = ops["dn"]
    Bb = ops["B_bnd"]
    Hb = ops["H_bnd"]

    if np.isscalar(a):
        closure = -HI @ e @ Hb @ (Bb @ dn.T + a * e.T)
    else:
        A = diags_array(a)
        closure = -HI @ e @ Hb @ (Bb @ dn.T + A @ e.T)
    penalty = -HI @ e @ Hb

    return closure, penalty


def solve_and_plot(
    grid, u_fun, b_fun=lambda x: 0.0 * x + 1, bc_type="dirichlet", PLOT=True
):
    """Demo function that shows how to build the SBP discretization for a given grid, then solve the Poisson equation, and plot the solution."""

    # --- Boundary condition settings ---
    bc_opts = {"type": bc_type}

    # Parameter a in Robin BC (not needed for Dirichlet)
    if bc_type == "robin":
        bc_opts["a"] = 2
    # -----------------------------------

    # Evaluate functions on the grid
    Xv = grid["Xv"]
    Yv = grid["Yv"]
    u = u_fun(Xv, Yv)
    b = b_fun(Xv, Yv)

    # Build discretization for Dirichlet BC,
    order = 5  # Interior order of accuracy of SBP operators
    sbp_discr = assemble_matrices(grid, order, b, bc_opts)

    # Solve the discretized equation (a linear system)
    Laplace_with_BC = sbp_discr["Laplace_with_BC"]
    sol = spsplg.spsolve(Laplace_with_BC, u)

    # Equivalent way to solve the system of equations:
    # sol = sbp_discr['poisson_solver'](u)

    if PLOT:
        # Matrices of grid coordinates
        X = grid["X"]
        Y = grid["Y"]

        # Reshape vectors into 2D arrays
        U = np.reshape(u, X.shape)
        B = np.reshape(b, X.shape)
        SOL = np.reshape(sol, X.shape)

        # Figure with sublots
        fig, axes = plt.subplots(3, 1)

        # Plot source u
        im1 = axes[0].pcolormesh(X, Y, U, shading="auto")
        axes[0].set_xlabel("x")
        axes[0].set_ylabel("y")
        axes[0].set_title("Source u")
        fig.colorbar(im1, ax=axes[0])

        # Plot coefficient b
        im2 = axes[1].pcolormesh(X, Y, B, shading="auto")
        axes[1].set_xlabel("x")
        axes[1].set_ylabel("y")
        axes[1].set_title("Coefficient b")
        fig.colorbar(im2, ax=axes[1])

        # Plot solution y
        im3 = axes[2].pcolormesh(X, Y, SOL, shading="auto")
        axes[2].set_xlabel("x")
        axes[2].set_ylabel("y")
        axes[2].set_title(
            f"numerical solution y, order={order}, BC type = {bc_opts['type']}"
        )
        fig.colorbar(im3, ax=axes[2])

        plt.tight_layout()
        plt.show()

    return sol, sbp_discr


def shifted_gaussian(x, y, x0=0.0, y0=0.0, sigma=0.2):
    return np.exp(-0.5 * (((x - x0) / sigma) ** 2 + ((y - y0) / sigma) ** 2))


def example_u(x, y):
    """Example source function"""
    return shifted_gaussian(x, y, 0, 0.5, 0.2)


def example_b(x, y):
    # b=1 for the standard Poisson equation
    return 1.0 + 0 * x

    # Variable-coefficient Poisson equation
    # return 1.0 + 10*shifted_gaussian(x, y, 0.2, 0.5, 0.1)


def main():
    """Demo"""

    # Domain boundaries
    lim_x = [-1, 1]
    lim_y = [0, 1]

    # Create grid
    mx = 61
    my = 31
    grid = create_grid(mx, my, lim_x, lim_y)

    # Build SBP-SAT discretization,
    # solve Poisson equation, and plot.
    y, sbp_discr = solve_and_plot(grid, example_u, example_b, PLOT=True)


if __name__ == "__main__":
    main()
